### ISSUE TITLE
老哥win程序内置的下载浏览器源G了 手动下载的识别不了  能教教我吗

### ISSUE THREAD

**Issue by Retireee** [iiidcc/autojdck#1]

**Comment by iiidcc** [comment]
win系统chrome浏览器手动下载地址 下载地址：https://mirrors.huaweicloud.com/chromium-browser-snapshots/Win_x64/884014/chrome-win.zip 然后 解压到（没有路径就创建路径） C:\Users<用户名>\AppData\Local\pyppeteer\pyppeteer\local-chromium\588429\chrome-win32
